"""Update table with tasks

Revision ID: 5ac484241377
Revises: 84b2b9ee7ccd
Create Date: 2024-11-28 20:18:33.101565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ac484241377'
down_revision: Union[str, None] = '84b2b9ee7ccd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('category', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'category')
    # ### end Alembic commands ###
