"""Create tasks table

Revision ID: ba2ecd4cf808
Revises: 451ffbf597d2
Create Date: 2024-11-28 00:18:59.563325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba2ecd4cf808'
down_revision: Union[str, None] = '451ffbf597d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('gifs_points', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('users', 'category',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=35),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'category',
               existing_type=sa.String(length=35),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
    op.drop_table('tasks')
    # ### end Alembic commands ###
